### ISSUE TITLE
attempting to build using 1.6.8

### ISSUE THREAD

**Issue by RawLiquid** [togglebit/ArduinoDUE_OBD_FreeRunningCAN#2]
I attempted with the library folder named CAN, can, and OBD2, all with the same result. It's almost as if it's not allowing the custom variant.h file to load...

Arduino: 1.6.8 (Windows 10), Board: "Arduino Due (Programming Port)"

In file included from C:\Users\Nathan\Documents\Arduino\libraries\OBD2/OBD2.h:18:0,

```
             from C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino:1:
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:121:5: error: 'UINT32' does not name a type

```
 UINT32 ID;      

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:132:9: error: 'UINT8' does not name a type

```
     UINT8 b[8];

     ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:136:13: error: 'UINT32' does not name a type

```
         UINT32 lowerPayload;

         ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:137:13: error: 'UINT32' does not name a type

```
         UINT32 upperPayload;

         ^
```

In file included from C:\Users\Nathan\Documents\Arduino\libraries\OBD2/OBD2.h:18:0,

```
             from C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino:1:
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:239:5: error: 'UINT32' does not name a type

```
 UINT32 getTimeSlice(bool max);

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:267:5: error: 'UINT32' does not name a type

```
 UINT32 getTxCtr();

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:274:5: error: 'UINT32' does not name a type

```
 UINT32 getRxCtr();

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:291:5: error: 'UINT32' does not name a type

```
 UINT32 count, prevCount, ticks, usTicks;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:296:5: error: 'UINT16' does not name a type

```
 UINT16 _1mSCntr, _10mSCntr, _100mSCntr, _200mSCntr, _1000mSCntr, _queryCntr;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:301:5: error: 'UINT32' does not name a type

```
 UINT32 usTsliceEnd, usTslice, usTsliceMax;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:316:5: error: 'UINT8' does not name a type

```
 UINT8 msgCntRx;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:317:5: error: 'UINT8' does not name a type

```
 UINT8 msgCntTx;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:318:5: error: 'UINT8' does not name a type

```
 UINT8 msgCntQuery;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:323:5: error: 'UINT8' does not name a type

```
 UINT8 queryIndex;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:328:5: error: 'UINT32' does not name a type

```
 UINT32 RxCtr;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:329:5: error: 'UINT32' does not name a type

```
 UINT32 TxCtr;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:338:5: error: 'UINT32' does not name a type

```
 UINT32 MAM_mask;

 ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/CAN_Acquisition.h:339:5: error: 'UINT32' does not name a type

```
 UINT32 MID_mask;                                                     

 ^
```

In file included from C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino:1:0:

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/OBD2.h:145:2: error: 'UINT32' does not name a type

  UINT32 getIntData();

  ^

C:\Users\Nathan\Documents\Arduino\libraries\OBD2/OBD2.h:223:9: error: 'UINT8' does not name a type

  static UINT8  listIdx;

```
     ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino: In function 'void setup()':

CAN_BoardTest:36: error: 'class cCANFrame' has no member named 'ID'

```
 RAW_CAN_Frame1.ID    = 0x100;

                ^
```

CAN_BoardTest:38: error: 'class cCANFrame' has no member named 'ID'

```
 RAW_CAN_Frame2.ID    = 0x101;

                ^
```

C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino: At global scope:

CAN_BoardTest:56: error: 'UINT8' does not name a type

 UINT8 i,CAN0_rxCtr,CAN1_rxCtr;

 ^

CAN_BoardTest:57: error: 'UINT32' does not name a type

 UINT32 maxTime;

 ^

CAN_BoardTest:58: error: 'UINT8' does not name a type

 UINT8 passFail;

 ^

C:\Users\Nathan\Documents\Arduino\libraries\OBD2\CAN_BoardTest\CAN_BoardTest.ino: In function 'void loop()':

CAN_BoardTest:63: error: 'passFail' was not declared in this scope

```
 passFail =  true;

 ^
```

CAN_BoardTest:66: error: 'CAN0_rxCtr' was not declared in this scope

```
 if (CAN0_rxCtr != CANport0.getRxCtr())

     ^
```

CAN_BoardTest:66: error: 'class cAcquireCAN' has no member named 'getRxCtr'

```
 if (CAN0_rxCtr != CANport0.getRxCtr())

                            ^
```

CAN_BoardTest:77: error: 'CAN0_rxCtr' was not declared in this scope

```
 CAN0_rxCtr = CANport0.getRxCtr();

 ^
```

CAN_BoardTest:77: error: 'class cAcquireCAN' has no member named 'getRxCtr'

```
 CAN0_rxCtr = CANport0.getRxCtr();

                       ^
```

CAN_BoardTest:80: error: 'CAN1_rxCtr' was not declared in this scope

```
 if (CAN1_rxCtr != CANport1.getRxCtr())

     ^
```

CAN_BoardTest:80: error: 'class cAcquireCAN' has no member named 'getRxCtr'

```
 if (CAN1_rxCtr != CANport1.getRxCtr())

                            ^
```

CAN_BoardTest:91: error: 'CAN1_rxCtr' was not declared in this scope

```
 CAN1_rxCtr = CANport1.getRxCtr();

 ^
```

CAN_BoardTest:91: error: 'class cAcquireCAN' has no member named 'getRxCtr'

```
 CAN1_rxCtr = CANport1.getRxCtr();

                       ^
```

exit status 1
'class cCANFrame' has no member named 'ID'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by togglebit** [comment]
Yeah I'm sorry about this someone else just brought it to my attention last
week I need to revise the instructions. If you copy and paste the typedefs
I added in the variant.H into the can acquisition.H I think you'll be good
to go. Can you please let me know if this works and also let me know what
version of the IDE you are on? I appreciate your feedback and would also
like to hear about your project.

Thanks,
Dan

**Comment by RawLiquid** [comment]
Yes, that did resolve the errors, and I had tried it using 1.6.7, 1.6.8, 1.6.2, 1.6.0.

My intention is to attempt controlling my cars stereo based on things detected by the arduino, initially I will be trying to pause whatever is playing for some amount of time whenever audio data is detected on an analog input which is tied into the output of my ham radio and/or CB.
The idea being to add a level of integration currently unavailable and allow the stereo to be used without sacrificing the ability to be reached via radio.

**Comment by RawLiquid** [comment]
one quick comment about the board, not intending to detract any from what you have produced, and I have yet to use it as I just received it, but given the choice, I would opt for a board that had the connections at the opposite end, and constrained to match the Due's footprint. Even if it meant sacrificing some of the proto area, to allow any existing case that people have to continue to be used. Mine happens to be aluminum and using it with this board will require doubling up the headers, ie putting a set that are not soldered to a board in, then stacking this board into those headers in order to raise the board up some.
